### ISSUE TITLE
Support Function Chaining

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/apiRAG#17]
Support use cases where the model uses the output from a prior function call to call another function.

For example, look up a customer id by customer phone number and then look up customer information by customer id.

**Comment by bilbo7833** [comment]
@mbroecheler I'm not sure what more needs to be done here. I have seen the model get one function call response and then call another function afterwards.

**Comment by mbroecheler** [comment]
Yes, you are right. I confused this with #20.
